name: Monitoramento de Logs

on:
  workflow_dispatch:

jobs:
  monitoramento:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install pandas

      - name: Executar script de monitoramento
        run: python monitor_logs.py

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: logs_csv
          path: eventos_seguranca.csv
